version: '3.9'

services:
  php-fpm:
    build:
      context: ./build/php81
      args:
        - PHP_FPM_VERSION=${PHP_VERSION}
    container_name: ${PROJECT_NAME}-php
    volumes:
      - ./www/${APP_ROOT_DIR}:/var/www/html:cached
    expose:
      - "9000"
    networks:
      - ${SYSTEM_NETWORK}
      - app_network

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./www/${APP_ROOT_DIR}:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - php-fpm
    networks:
      - ${SYSTEM_NETWORK}
      - app_network

networks:
  app_network:
    name: app_network
    driver: bridge
  system_network:
    external: true

